menu:
  - code: "首页"
    type: "home"
    title: "首页"
    href: "layuimini/page/welcome-1.html?t=1"
    is_shown: 1
  - code: "LAYUI MINI"
    type: "logo"
    title: "LAYUI MINI"
    image: "layuimini/images/logo.png"
    href: ""
    is_shown: 1
  - code: "常规管理"
    type: "head"
    title: "常规管理"
    icon: "fa fa-address-book"
    href: ""
    target: "_self"
    child: "主页模板"
    is_shown: 1
  - code: "主页模板"
    type: "directory"
    title: "主页模板"
    icon: "fa fa-home"
    href: ""
    target: "_self"
    child: "主页一|主页二|主页三"
    is_shown: 1
  - code: "主页一"
    type: "menu"
    title: "主页一"
    href: "layuimini/page/welcome-1.html"
    icon: "fa fa-tachometer"
    target: "_self"
    is_shown: 1
  - code: "主页二"
    type: "menu"
    title: "主页二"
    href: "layuimini/page/welcome-2.html"
    icon: "fa fa-tachometer"
    target: "_self"
    is_shown: 1
  - code: "主页三"
    type: "menu"
    title: "主页三"
    href: "layuimini/page/welcome-3.html"
    icon: "fa fa-tachometer"
    target: "_self"
    is_shown: 0
  - code: "菜单管理"
    type: "menu"
    title: "菜单管理"
    icon: "fa fa-window-maximize"
    href: "layuimini/page/menu.html"
    target: "_self"
    is_shown: 1