name: Code Quality Check

on:
  push:
    branches:
      - master

jobs:
  code_quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19  # 选择您的 Go 版本

      - name: Run Go Vet
        run: go vet ./...

      - name: Install gocyclo
        run: go get -u github.com/fzipp/gocyclo
      - name: Add gocyclo to PATH
        run: export PATH=$PATH:$(go env GOPATH)/bin
      - name: Run gocyclo
        run: gocyclo .